name: "Nuclei Action"
description: "Nuclei is a fast and customisable vulnerability scanner based on simple YAML based DSL"

inputs:
  url:
    description: "The URL to scan"
    required: true
  output:
    description: "File to save output result"
    required: false
    default: "nuclei.log"
  user-agent:
    description: "Set a User-Agent header"
    required: false
    default: "Nuclei - Open-source project (github.com/projectdiscovery/nuclei)"

runs:
  using: "composite"
  steps:
    - run: |
        [ ! -x /home/runner/go/bin/nuclei ] && GO111MODULE=on go get -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei
        echo "/home/runner/go/bin/" >> $GITHUB_PATH
      shell: bash

    - run: |
        mkdir nuclei-templates
        nuclei -ut -ud ./nuclei-templates

        nuclei \
          -target ${{ inputs.url }} \
          -t ./nuclei-templates \
          -o ${{ inputs.output }} \
          -H "User-Agent: ${{ inputs.user-agent }}" \
          -json \
          -include-rr \
          \
      shell: bash
